export const ActionType = {
    GET_PRODUCTS: 'GET_PRODUCTS',
    SELECT_PRODUCT: 'SELECT_PRODUCT',
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    GET_CART: 'GET_CART',
    GET_CART_TOTAL: 'GET_CART_TOTAL',
    GET_CART_ITEM_COUNT: 'GET_CART_ITEM_COUNT',
}